"""add content_id to asset_news

Revision ID: 968f674c4966
Revises: bf50acbd99eb
Create Date: 2026-03-16 14:41:03.151264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '968f674c4966'
down_revision: Union[str, Sequence[str], None] = 'bf50acbd99eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_news', sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('asset_news', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_asset_news_content_id'), 'asset_news', ['content_id'], unique=False)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_asset_news_content_id'), table_name='asset_news')
    op.alter_column('asset_news', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('asset_news', 'content_id')
    # ### end Alembic commands ###
