"""add source_type and asset_id_nullable to asset_news

Revision ID: a2366658d374
Revises: 968f674c4966
Create Date: 2026-03-17 11:19:48.561983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2366658d374'
down_revision: Union[str, Sequence[str], None] = '968f674c4966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sourcetype_enum = sa.Enum('yfinance', name='sourcetype')
    sourcetype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('asset_news', sa.Column('source_type', sa.Enum('yfinance', name='sourcetype', create_type=False), nullable=False))
    op.alter_column('asset_news', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_news', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('asset_news', 'source_type')
    sa.Enum(name='sourcetype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
